dist: xenial
language: cpp
services: docker

before_install:
  - docker pull neonsky/neon-engine
  - make docker-linter-build

script:
  - make docker-linter-run

branches:
  only:
    - master

notifications:
  email: false
